name = "JSXGraph"
uuid = "97e4c2e4-f0cb-461e-a268-312dec255b76"
authors = ["Thibaut Lienart <ltib@me.com>"]
version = "0.1.6"

[deps]
Blink = "ad839575-38b3-5650-b840-f874b8c74a25"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
JSExpr = "97c1335a-c9c5-57fe-bc5d-ec35cebe8660"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Blink = "0.12"
DocStringExtensions = "0.8"
JSExpr = "0.5"
OrderedCollections = "1.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
